### ISSUE TITLE
Crash caused by undefined in D-Bus message

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/almond-gnome#2]
at <anonymous>
 at /app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/bus.js:111:29
 at EventEmitter.self.message (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/index.js:128:28)
 at Object.marshallMessage [as marshall] (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/message.js:86:16)
 at marshall (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:20:13)
 at writeStruct (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:34:5)
 at write (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:61:9)
 at write (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:44:7)
 at writeStruct (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:34:5)
 at write (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:79:7)
 at write (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:82:14)
 at writeSimple (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/marshall.js:90:11)
Error: Serialisation of JS 'undefined' type is not supported by d-bus

**Comment by gcampax** [comment]
Unfortunately, the stack trace is useless, so I am forced to close this issue.
